[main]
font=Iosevka Nerd Font:pixelsize=14
pad=20x20

[colors-dark]
background={{colors.background.default.hex_stripped}}
foreground={{colors.on_background.default.hex_stripped}}

#regular0={{colors.surface_container_lowest.default.hex_stripped}}
#regular1={{colors.error.default.hex_stripped}}
#regular2={{colors.primary.default.hex_stripped}}
#regular3={{colors.tertiary.default.hex_stripped}}
#regular4={{colors.secondary.default.hex_stripped}}
#regular5={{colors.primary_container.default.hex_stripped}}
#regular6={{colors.secondary_container.default.hex_stripped}}
#regular7={{colors.on_surface.default.hex_stripped}}

#bright0={{colors.surface_container_high.default.hex_stripped}}
#bright1={{colors.error_container.default.hex_stripped}}
#bright2={{colors.primary_fixed.default.hex_stripped}}
#bright3={{colors.tertiary_container.default.hex_stripped}}
#bright4={{colors.secondary_fixed.default.hex_stripped}}
#bright5={{colors.primary_fixed_dim.default.hex_stripped}}
#bright6={{colors.secondary_fixed_dim.default.hex_stripped}}
#bright7={{colors.on_surface_variant.default.hex_stripped}}


regular0=494d64
regular1=ed8796
regular2=a6da95
regular3=eed49f
regular4=8aadf4
regular5=f5bde6
regular6=8bd5ca
regular7=b8c0e0

bright0=5b6078
bright1=ed8796
bright2=a6da95
bright3=eed49f
bright4=8aadf4
bright5=f5bde6
bright6=8bd5ca
bright7=a5adcb


selection-background={{colors.primary_container.default.hex_stripped}}
selection-foreground={{colors.on_primary_container.default.hex_stripped}}
